# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-03 11:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_check_nag'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='nagtime',
            field=models.DurationField(default=datetime.timedelta(0, 10800)),
        ),
    ]
