# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-03 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_check_nagtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='last_nag',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
